apiVersion: v1
kind: PersistentVolume
metadata:
  name: dp-pv
  labels:
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/postgres/data"