apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  labels:  
    app: redis
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi