---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: back
      role: redis
      app:  redis
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: redis
        role: redis
        tier: back
        version: latest
    spec:
      containers:
      - image: redis:6.2-alpine3.13
        imagePullPolicy: Always
        name: redis
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: redis
            mountPath: /etc/redis.conf
          protocol: TCP
      volumes:
      - name: redis
        persistentVolumeClaim:
          claimName: redis-pvc
      restartPolicy: Always