apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  revisionHistoryLimit: 4
  paused: false
  replicas: 2
  minReadySeconds: 20
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      name: vote
      labels:
        result: result
    spec:
      containers:
        - name: app
          image: schoolofdevops/vote-result
          resources:
            limits:
              cpu: 2
              memory: 128Mi
            requests:
              cpu: 1
              memory: 64Mi
          ports:
            - containerPort: 80
              protocol: TCP